// This file is auto-generated by @hey-api/openapi-ts

export type GetLatergramData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/latergram/';
};

export type GetLatergramResponses = {
    200: string;
};

export type GetLatergramResponse = GetLatergramResponses[keyof GetLatergramResponses];

export type GetLatergramByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/latergram/{id}';
};

export type GetLatergramByIdResponses = {
    200: string;
};

export type GetLatergramByIdResponse = GetLatergramByIdResponses[keyof GetLatergramByIdResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    200: string;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};