// This file is auto-generated by @hey-api/openapi-ts

export type GetLatergramData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/latergram/';
};

export type GetLatergramResponses = {
    200: unknown;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    200: string;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};